services:
  foxglove:
    build: .
    network_mode: host
    # ports:
    #   - 8080:8080
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080

  rosbridge:
    image: husarion/rosbridge-server:humble
    network_mode: host
    # ports:
    #   - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  
