services:
  foxglove:
    build:
      dockerfile: Dockerfile.foxglove
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090
    ports:
      - 8080:8080

  rosbridge:
    image: husarion/rosbridge:humble-nightly
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  