x-common-config: &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROBOT_NAMESPACE=panther
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

services:
  webui:
    image: husarion/foxglove:studio-20240723
    <<: *common-config
    volumes:
      - ./foxglove-layout.json:/foxglove/default-layout.json

  webui-ds:
    image: husarion/foxglove-bridge:humble-0.7.7-20240708
    <<: *common-config
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
