services:
  foxglove:
    image: husarion/foxglove:studio-nightly
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    # runtime: nvidia
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./foxglove-layout.json:/foxglove/default-layout.json
    environment:
      - DS_HOST=foxglove-ds
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.4-20240320
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,parameters,parametersSubscribe,services,connectionGraph,assets]
