services:
  foxglove:
    # image: husarion/foxglove:1.74.1
    build:
      context: ..
      dockerfile: ./Dockerfile
    network_mode: bridge  # using docker0 interface
    ports:
      - 8080:8080
      - "[::]:8765:8765"
    volumes:
      - ./foxglove_layout.json:/foxglove/default-layout.json
      - ../Caddyfile:/etc/caddy/Caddyfile
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=172.17.0.1 # docker0 interface address for host machine
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  # foxglove-bridge can not listen on the IPv6 network, so when used with Husarnet it requires a reverse proxy that is activated in the foxglove
  # service above. The proxy is configured in the Caddyfile_reverse_proxy file.
  foxglove-datasource:
    image: husarion/foxglove-bridge:humble
    network_mode: host
    environment:
      - ROS_LOCALHOST_ONLY=1
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,connectionGraph,assets]
