services:

  foxglove:
    image: husarion/foxglove:improvements-nightly
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./foxglove-layout.json:/foxglove/default-layout.json
    environment:
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.7-20240708
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    ports:
      - 8765:8765
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,parameters,parametersSubscribe,services,connectionGraph,assets]
