services:
  foxglove:
    image: husarion/foxglove:v1.72.0
    ports:
      - 8080:8080
    volumes:
      - ./RosbotTeleop.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080

  rosbridge:
    image: husarion/rosbridge-server:humble
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  
