services:
  foxglove:
    image: husarion/foxglove:1.72.0
    # build:
    #   context: ..
    #   dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./RosbotTeleop.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  rosbridge:
    image: husarion/rosbridge-server:humble
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml
