services:
  foxglove:
    image: husarion/foxglove:humble
    volumes:
      - ./RosbotTeleop.json:/src/FoxgloveDefaultLayout.json
    environment:
      - FOXGLOVE_PORT=8080
    ports:
      - 8080:8080

  rosbridge:
    image: husarion/rosbridge-server:humble
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  