name: Build a Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set SHORT_DATE env
        run: echo "SHORT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (production)
        if: github.ref_name == 'main' || github.ref_name == 'studio'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            husarion/foxglove:${{ github.head_ref || github.ref_name }}-${{ env.SHORT_DATE }}
            husarion/foxglove:${{ github.head_ref || github.ref_name }}
            husarion/foxglove:${{ github.head_ref || github.ref_name }}-nightly
          cache-to: type=inline

      - name: Build and push (feature branch)
        if: github.ref_name != 'main' && github.ref_name != 'studio'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            husarion/foxglove:${{ github.head_ref || github.ref_name }}-nightly
          cache-to: type=inline
